---
- name: Include distro-specific zsh install
  ansible.builtin.include_tasks: "{{ distro_family }}.yml"

- name: Get zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Ensure zsh is in /etc/shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
    state: present

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
  when: ansible_env.SHELL | basename != 'zsh'
